#pragma once
#include "RegisterNewSensorException.h"
#include "DisableSensorException.h"
#include "EnableSensorException.h"
#include "RemoveSensorException.h"
#include "UpdateBatteryException.h"
#include "PinException.h"
#include "BindFailedException.h"
#include "OAuth2Exception.h"