#include "RegisterNewSensorException.h"
#include "DisableSensorException.h"
#include "EnableSensorException.h"
#include "RemoveSensorException.h"
#include "UpdateBatteryException.h"
#include "PinException.h"
#include "Logger.h"